- hosts: localhost
  vars_files:
          - files.yml
  tasks:          
  - name: "launching webservers in aws cloud "
    ec2:
       assign_public_ip: yes
       aws_access_key: "{{ x }}"
       aws_secret_key: "{{ y }}"
       count: 3
       wait: yes
       wait_timeout: 50
       image: ami-0a9d27a9f4f5c0efc
       group_id: sg-53ab7134
       instance_tags:
               Name: Webserver
               country: IN
               ENV: PROD
       instance_type: t2.micro
       key_name: prabalkey
       region: ap-south-1
       state: present
       vpc_subnet_id: subnet-2339304b
    register: wb

  - name: updating wb inventroy
    blockinfile:
      path: /root/ansible_ws/aws_ws/inventory/wb
      create: yes
      block: |
          [webservers]
          {{ wb.instances[0].public_ip }}
          {{ wb.instances[1].public_ip }}
          {{ wb.instances[2].public_ip }}
